# Generated by Django 5.2 on 2025-04-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sample_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sample Dataset',
                'verbose_name_plural': 'Sample Datasets',
            },
        ),
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_uploads/%Y/%m/%d/')),
                ('file_path', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('upload', 'Uploaded File'), ('record', 'Browser Recording'), ('sample', 'Sample Dataset')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(max_length=100)),
                ('dataset', models.CharField(blank=True, max_length=50, null=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('sample_metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('surprised', 'Surprised')], max_length=20)),
                ('confidence', models.FloatField()),
                ('full_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_result', to='emotion_recognition.audiorecord')),
            ],
        ),
    ]
